FROM python:3.10-slim

WORKDIR /app

# system deps
RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# install python deps
COPY training/requirements.training.txt .
RUN pip install --no-cache-dir -r requirements.training.txt

# copy training code
COPY training/ ./training/

# entrypoint
ENTRYPOINT ["python", "training/run_pipeline.py"]
