FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*

# Install dependencies
COPY api/requirements.api.txt .
RUN pip install --no-cache-dir -r requirements.api.txt

# API code
COPY api ./api

# API-owned model
COPY api/model ./model

ENV PYTHONUNBUFFERED=1

CMD ["uvicorn", "api.api:app", "--host", "0.0.0.0", "--port", "8000"]
