FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY api/requirements.api.txt .
RUN pip install --no-cache-dir -r requirements.api.txt

# Copy API code
COPY api /app/api

# Copy trained model artifacts
COPY training/models /app/models

EXPOSE 80

ENTRYPOINT ["uvicorn", "api.api:app", "--host", "0.0.0.0", "--port", "80"]
